import React from 'react';
import type { Metadata } from "next";
// Using Inter font as it closely matches the design
import { Inter } from 'next/font/google'; 
import "./globals.css";
import { Providers } from './Providers';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  // Disable automatic <link rel="preload"> generation to avoid
  // preload warnings when the font isn't used immediately.
  // If you prefer preloading, set this to `true` and ensure the
  // font is referenced early in the page (or add appropriate `as`/`crossorigin`).
  preload: false,
});

export const metadata: Metadata = {
  title: "XYTON Design Tool",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      {/* Using the Inter font variable defined above.
        Ensuring the app is full-height and hides overflow.
      */}
      <body
        className={`${inter.variable} font-sans antialiased h-screen w-screen overflow-hidden`}
      >
        {/* Inline script to apply system preference theme immediately before React mounts.
            This prevents pages appearing stuck due to hydration timing. */}
        <script dangerouslySetInnerHTML={{ __html: `
          (function(){
            try {
              var prefersDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
              var theme = prefersDark ? 'dark' : 'light';
              var html = document.documentElement;
              if (theme === 'dark') {
                html.classList.add('dark');
                html.setAttribute('data-theme','dark');
              } else {
                html.classList.remove('dark');
                html.setAttribute('data-theme','light');
              }
            } catch (e) { /* ignore */ }
          })();
        ` }} />
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}